import fs from "fs";
import path from "path";
import { compile, JSONSchema } from "json-schema-to-typescript";
// @ts-ignore
import * as changeCase from "change-case";

export const generateFunctionImport = (apiNameList: string[]) => {
  let content = "";
  content += `import { ajax } from 'qdll-business'\n`;
  content += `import { ${apiNameList
    .map((name) => changeCase.pascalCase(name))
    .join(", ")} } from './types';`;
  content += `\nconst { post, postPage } = ajax`;
  return content;
};

export const generateFunction = ({
  name,
  url,
  method = "post",
  originName,
}: {
  name: string;
  url: string;
  originName: string;
  method?: string;
}) => {
  return `/**
 * ${originName}
 */
export const ${name} = async (params: ${changeCase.pascalCase(name)}Params) => 
    ${method}<${changeCase.pascalCase(name)}Res>('${url}', params);
  `;
};

export const generateTypes = async (name: string, data: JSONSchema) => {
  return await compile(data, name, {
    additionalProperties: false,
    bannerComment: "",
  });
};

export const generateFiles = (folderPath: string) => {
  if (!fs.existsSync(folderPath)) {
    fs.mkdirSync(folderPath, { recursive: true });
  }
  fs.writeFileSync(
    path.join(folderPath, "index.ts"),
    "export * from './types';\nexport * from './apis';"
  );
  fs.writeFileSync(
    path.join(folderPath, "types.ts"),
    "// This file is generated by qdll-generate-yapi"
  );
  fs.writeFileSync(
    path.join(folderPath, "apis.ts"),
    "// This file is generated by qdll-generate-yapi"
  );
};
